// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/data/tikvah-services.ts
var TIKVAH_INTRO = "A Tikvah estrutura os seus servi\xE7os como um ecossistema integrado, pensado para gerar impacto mensur\xE1vel em pessoas, organiza\xE7\xF5es e comunidades. Aliamos psicologia fundamentada em evid\xEAncia, gest\xE3o estrat\xE9gica, tecnologia, direito, finan\xE7as e responsabilidade social num modelo de interven\xE7\xE3o centrado em efici\xEAncia, rigor t\xE9cnico e sustentabilidade.";
var TIKVAH_CATEGORIES = [
  {
    id: "saude-mental",
    title: "Sa\xFAde mental, reabilita\xE7\xE3o e interven\xE7\xE3o",
    short: "Sa\xFAde Mental",
    summary: "Avalia\xE7\xE3o, psicoterapia e reabilita\xE7\xE3o multidisciplinar com foco em autonomia e bem-estar.",
    gradient: "from-teal-600 to-emerald-600",
    accent: "text-emerald-600",
    icon: "brain",
    items: [
      {
        title: "Psicologia cl\xEDnica, social e organizacional",
        description: "Avalia\xE7\xE3o psicol\xF3gica, formula\xE7\xE3o de caso, planeamento de interven\xE7\xE3o individualizado e acompanhamento continuado, com foco em sa\xFAde mental, trauma, resili\xEAncia e desempenho pessoal e profissional."
      },
      {
        title: "Terapia da Fala",
        description: "Avalia\xE7\xE3o fon\xE9tica, fonol\xF3gica e lingu\xEDstica, com reabilita\xE7\xE3o de perturba\xE7\xF5es de fala, comunica\xE7\xE3o e linguagem em desenvolvimento infantil e reabilita\xE7\xE3o de adultos."
      },
      {
        title: "Terapia da Fala em L\xEDngua Gestual",
        description: "Apoio especializado a pessoas com defici\xEAncia auditiva, focado em comunica\xE7\xE3o acess\xEDvel, media\xE7\xE3o lingu\xEDstica, integra\xE7\xE3o escolar e ajuste de materiais pedag\xF3gicos e institucionais."
      },
      {
        title: "Terapia Ocupacional",
        description: "Avalia\xE7\xE3o funcional e (re)habilita\xE7\xE3o de atividades de vida di\xE1ria, com foco em autonomia, participa\xE7\xE3o social e adapta\xE7\xE3o de ambientes dom\xE9sticos, educativos e cl\xEDnicos."
      },
      {
        title: "Apoio psicol\xF3gico em crises",
        description: "Interven\xE7\xE3o protocolada em situa\xE7\xF5es de emerg\xEAncia, desastre, trauma, viol\xEAncia e transi\xE7\xF5es cr\xEDticas, com equipas de resposta r\xE1pida e suporte a v\xEDtimas e acompanhantes."
      },
      {
        title: "Terapias individuais, familiares e de grupo",
        description: "Programas terap\xEAuticos estruturados baseados em evid\xEAncia (TCC, abordagens sist\xE9micas e outras modalidades), com metas de curto, m\xE9dio e longo prazo."
      }
    ]
  },
  {
    id: "formacao",
    title: "Forma\xE7\xE3o, est\xE1gios, P&D e capacita\xE7\xE3o avan\xE7ada",
    short: "Forma\xE7\xE3o & P&D",
    summary: "Cursos certificados, est\xE1gios supervisionados e investiga\xE7\xE3o aplicada em sa\xFAde mental e ci\xEAncias sociais.",
    gradient: "from-blue-600 to-indigo-600",
    accent: "text-blue-600",
    icon: "graduation",
    items: [
      {
        title: "Cursos e treinamentos",
        description: "Forma\xE7\xE3o t\xE9cnica, psicol\xF3gica, organizacional e socioeducativa, com foco em transfer\xEAncia de compet\xEAncias pr\xE1ticas para contextos de sa\xFAde, educa\xE7\xE3o, justi\xE7a e sociedade civil."
      },
      {
        title: "Primeiros Socorros Psicol\xF3gicos (PSP)",
        description: "M\xF3dulos de resgate psicol\xF3gico inicial, resposta em desastres e apoio em emerg\xEAncias, dirigidos a profissionais de sa\xFAde, educa\xE7\xE3o, seguran\xE7a p\xFAblica e organiza\xE7\xF5es de socorro."
      },
      {
        title: "Est\xE1gios supervisionados",
        description: "Est\xE1gios cl\xEDnicos, educativos e comunit\xE1rios em psicologia, terapia da fala, terapia ocupacional, sa\xFAde mental e interven\xE7\xE3o social, com supervis\xE3o regular e contrato de est\xE1gio."
      },
      {
        title: "Programas de Est\xE1gio Profissional (PEP)",
        description: "Est\xE1gios pr\xE1ticos em contexto de mercado, desenhados em parceria com institui\xE7\xF5es de ensino superior e organiza\xE7\xF5es de sa\xFAde, educa\xE7\xE3o e servi\xE7os sociais."
      },
      {
        title: "Monitoria e Avalia\xE7\xE3o de Projetos (M&E)",
        description: "Desenvolvimento de indicadores, quadros l\xF3gicos, planos de avalia\xE7\xE3o e sistemas de relatoria de impacto para projetos sociais, de sa\xFAde, educacionais e comunit\xE1rios."
      },
      {
        title: "Pesquisa e Desenvolvimento (P&D)",
        description: "Investiga\xE7\xE3o aplicada em psicologia, sa\xFAde mental, educa\xE7\xE3o, pol\xEDticas sociais, justi\xE7a, p\xF3s-desastre e modelos de interven\xE7\xE3o em contextos de vulnerabilidade."
      }
    ]
  },
  {
    id: "gestao-projetos",
    title: "Gest\xE3o de projetos, administra\xE7\xE3o e opera\xE7\xF5es institucionais",
    short: "Projetos & Opera\xE7\xF5es",
    summary: "Ciclo de projeto completo, gest\xE3o de ONGs, voluntariado estruturado e opera\xE7\xF5es institucionais.",
    gradient: "from-amber-500 to-orange-600",
    accent: "text-amber-600",
    icon: "briefcase",
    items: [
      {
        title: "Gest\xE3o completa de projetos sociais, de sa\xFAde e institucionais",
        description: "Diagn\xF3stico, planeamento, capta\xE7\xE3o de recursos, implementa\xE7\xE3o, monitoria, avalia\xE7\xE3o e relato de resultados, com foco em efic\xE1cia program\xE1tica."
      },
      {
        title: "Administra\xE7\xE3o e opera\xE7\xF5es",
        description: "Desenho de sistemas administrativos, fluxos de trabalho, manuais de procedimento, gest\xE3o documental e conformidade institucional."
      },
      {
        title: "Gest\xE3o de organiza\xE7\xF5es sem fins lucrativos",
        description: "Suporte em recursos humanos, log\xEDstica, contrata\xE7\xE3o de servidores e parceiros, e gest\xE3o de parcerias com ag\xEAncias e financiadores internacionais."
      },
      {
        title: "Voluntariado estruturado",
        description: "Programas em psicologia social, assist\xEAncia social, psicologia cl\xEDnica, educa\xE7\xE3o de inf\xE2ncia, nutri\xE7\xE3o, sa\xFAde e terapias, com ficha de enquadramento e avalia\xE7\xE3o de impacto."
      },
      {
        title: "Voluntariado comunit\xE1rio",
        description: "Apoio p\xF3s-desastre, atividades de sa\xFAde mental, sensibiliza\xE7\xE3o comunit\xE1ria, a\xE7\xF5es de limpeza, educa\xE7\xE3o e suporte psicossocial em parceria com comunidades locais."
      }
    ]
  },
  {
    id: "gestao-empresarial",
    title: "Gest\xE3o empresarial, neg\xF3cios, RH, economia e fiscalidade",
    short: "Empresarial & RH",
    summary: "Estrat\xE9gia, processos, pessoas e desempenho econ\xF3mico para PMEs e institui\xE7\xF5es.",
    gradient: "from-slate-700 to-slate-900",
    accent: "text-slate-700",
    icon: "scale",
    items: [
      {
        title: "Gest\xE3o Empresarial",
        description: "Diagn\xF3stico organizacional, defini\xE7\xE3o de estrat\xE9gia institucional, alinhamento de processos internos, gest\xE3o de mudan\xE7a e otimiza\xE7\xE3o do desempenho de equipas."
      },
      {
        title: "Gest\xE3o de Neg\xF3cios",
        description: "Planeamento estrat\xE9gico, modelagem de neg\xF3cio, objetivos de mercado, an\xE1lise de risco e indicadores de desempenho para organiza\xE7\xF5es de diversos setores."
      },
      {
        title: "Consultoria em Neg\xF3cios",
        description: "Conce\xE7\xE3o e implementa\xE7\xE3o de projetos comerciais, expans\xE3o de portf\xF3lio, reestrutura\xE7\xE3o de modelos operacionais e reengenharia de processos."
      },
      {
        title: "Gest\xE3o e Administra\xE7\xE3o de Recursos Humanos",
        description: "Recrutamento e sele\xE7\xE3o, avalia\xE7\xE3o de desempenho, planos de desenvolvimento, pol\xEDticas de carreira, remunera\xE7\xE3o, benef\xEDcios, clima e bem-estar no trabalho."
      },
      {
        title: "Planeamento de Recursos Humanos",
        description: "Estimativa de necessidades de pessoal, planeamento de sucess\xE3o, gest\xE3o de compet\xEAncias e alinhamento entre talento e estrat\xE9gia de longo prazo."
      },
      {
        title: "Gest\xE3o de Clima Organizacional",
        description: "Diagn\xF3sticos de ambiente de trabalho, resolu\xE7\xE3o de conflitos, gest\xE3o de stress e burnout, fortalecimento de cultura e culturas de seguran\xE7a e confian\xE7a."
      },
      {
        title: "An\xE1lise Econ\xF3mica aplicada",
        description: "Avalia\xE7\xE3o de impacto de pol\xEDticas e programas, an\xE1lise de custo-benef\xEDcio, modelagem de cen\xE1rios financeiros e suporte \xE0 decis\xE3o estrat\xE9gica."
      },
      {
        title: "Economia de Recursos Humanos",
        description: "Articula\xE7\xE3o entre RH, custos operacionais, produtividade e desempenho, com foco em reduzir desperd\xEDcios e melhorar o retorno do investimento em capital humano."
      },
      {
        title: "Contabilidade e Auditoria",
        description: "Sistemas contabil\xEDsticos, demonstra\xE7\xF5es financeiras, contabilidade de gest\xE3o, auditoria interna e garantia de transpar\xEAncia e conformidade regulat\xF3ria."
      },
      {
        title: "Fiscalidade corporativa",
        description: "Planeamento fiscal, enquadramento legal, obriga\xE7\xF5es de impostos, regulariza\xE7\xE3o de d\xE9bitos e orienta\xE7\xE3o em conformidade com a legisla\xE7\xE3o fiscal local."
      },
      {
        title: "Jurisprud\xEAncia aplicada",
        description: "Pareceres jur\xEDdicos, suporte em processos administrativos e contenciosos, com foco em direitos humanos, sa\xFAde mental, prote\xE7\xE3o de dados e responsabilidade institucional."
      },
      {
        title: "Assessoria empresarial e institucional",
        description: "Governan\xE7a, pol\xEDticas internas, gest\xE3o de risco, compliance e desenvolvimento de normas internas alinhadas com standards internacionais."
      }
    ]
  },
  {
    id: "tecnologia",
    title: "Tecnologia, inova\xE7\xE3o e comunica\xE7\xE3o",
    short: "Tecnologia",
    summary: "Infraestrutura segura, plataformas digitais especializadas e produ\xE7\xE3o de conte\xFAdos.",
    gradient: "from-violet-600 to-purple-700",
    accent: "text-violet-600",
    icon: "cpu",
    items: [
      {
        title: "Tecnologias de Informa\xE7\xE3o (TI)",
        description: "Gest\xE3o de infraestrutura de rede, sistemas de informa\xE7\xE3o, seguran\xE7a de dados, gest\xE3o documental eletr\xF3nica e suporte t\xE9cnico a equipas psicossociais e de campo."
      },
      {
        title: "Desenvolvimento de solu\xE7\xF5es digitais",
        description: "Plataformas para gest\xE3o de pacientes, sess\xF5es terap\xEAuticas, benefici\xE1rios, projetos, indicadores de impacto e M&E, com foco em seguran\xE7a, privacidade e usabilidade."
      },
      {
        title: "Publica\xE7\xF5es e M\xEDdia",
        description: "Produ\xE7\xE3o de conte\xFAdos t\xE9cnicos, divulgativos e educativos, relat\xF3rios institucionais, materiais de forma\xE7\xE3o, campanhas de sensibiliza\xE7\xE3o e comunica\xE7\xE3o digital."
      }
    ]
  },
  {
    id: "sustentabilidade",
    title: "Sustentabilidade, responsabilidade social e comunidade",
    short: "Comunidade & RSC",
    summary: "Programas de impacto social, outreach comunit\xE1rio e voluntariado alinhado a M&E.",
    gradient: "from-rose-600 to-pink-600",
    accent: "text-rose-600",
    icon: "handHeart",
    items: [
      {
        title: "Sustentabilidade organizacional",
        description: "Modelos de sustento a longo prazo, diversifica\xE7\xE3o de fontes de financiamento e integra\xE7\xE3o de pr\xE1ticas de responsabilidade social na miss\xE3o e valores."
      },
      {
        title: "Responsabilidade Social",
        description: "Desenho e implementa\xE7\xE3o de programas de impacto social em educa\xE7\xE3o, sa\xFAde, nutri\xE7\xE3o, prote\xE7\xE3o de grupos vulner\xE1veis e terapia comunit\xE1ria, com monitoria sistem\xE1tica."
      },
      {
        title: "Outreach e Suporte Comunit\xE1rio",
        description: "Interven\xE7\xF5es de proximidade, servi\xE7os m\xF3veis, sensibiliza\xE7\xE3o, grupos de apoio e parcerias com lideran\xE7as comunit\xE1rias e organiza\xE7\xF5es locais."
      },
      {
        title: "Engajamento comunit\xE1rio e voluntariado",
        description: "Programas estruturados e a\xE7\xF5es pontuais em sa\xFAde mental, educa\xE7\xE3o, assist\xEAncia b\xE1sica e apoio p\xF3s-desastre, alinhados a planos de programa e sistemas de M&E."
      }
    ]
  },
  {
    id: "assessoria",
    title: "Assessoria empresarial e financeira",
    short: "Assessoria",
    summary: "Apoio estrat\xE9gico e financeiro a startups, PMEs e profissionais em crescimento.",
    gradient: "from-sky-600 to-blue-700",
    accent: "text-sky-700",
    icon: "briefcase",
    items: [
      {
        title: "Assessoria Empresarial e Estrat\xE9gia de Crescimento",
        description: "Acompanhamento pr\xF3ximo a empreendedores e pequenas empresas na defini\xE7\xE3o de modelo de neg\xF3cio, plano de crescimento, estrutura\xE7\xE3o inicial e valida\xE7\xE3o de mercado, com foco na realidade econ\xF3mica de Mo\xE7ambique."
      },
      {
        title: "Assessoria Financeira e Desenvolvimento Profissional",
        description: "Apoio financeiro pessoal e profissional combinado com desenvolvimento de compet\xEAncias t\xE9cnicas e interpessoais, direcionado a indiv\xEDduos em transi\xE7\xE3o de carreira ou equipas em desenvolvimento."
      }
    ]
  },
  {
    id: "coaching-mentoria",
    title: "Coaching e mentoria",
    short: "Coaching",
    summary: "Coaching executivo, de carreira e de vida, e mentoria acad\xE9mica e profissional.",
    gradient: "from-emerald-600 to-teal-700",
    accent: "text-emerald-700",
    icon: "handHeart",
    items: [
      {
        title: "Coaching Executivo",
        description: "Programa estruturado de coaching individual para executivos e l\xEDderes organizacionais, com objetivos claros, sess\xF5es peri\xF3dicas e avalia\xE7\xE3o de progresso ao longo do percurso."
      },
      {
        title: "Coaching de Carreira e de Vida",
        description: "Acompanhamento individual para pessoas em transi\xE7\xE3o de carreira, procura de prop\xF3sito ou defini\xE7\xE3o de metas de vida, com plano de a\xE7\xE3o estruturado."
      },
      {
        title: "Mentoria Acad\xE9mica e Profissional",
        description: "Programa de mentoria para estudantes universit\xE1rios e profissionais juniores, com orienta\xE7\xE3o sobre percurso acad\xE9mico, primeiras experi\xEAncias profissionais e desenvolvimento de identidade profissional."
      }
    ]
  },
  {
    id: "programas-estruturados",
    title: "Programas estruturados de impacto",
    short: "Programas",
    summary: "Programas sistematizados de preven\xE7\xE3o e promo\xE7\xE3o de sa\xFAde mental para organiza\xE7\xF5es, escolas e fam\xEDlias.",
    gradient: "from-indigo-600 to-violet-700",
    accent: "text-indigo-700",
    icon: "brain",
    items: [
      {
        title: "Programa de Preven\xE7\xE3o e Manejo do Burnout",
        description: "Programa institucional com psicoeduca\xE7\xE3o sobre estresse ocupacional, autorregula\xE7\xE3o psiconeurofisiol\xF3gica e reorganiza\xE7\xE3o de processos laborais para reduzir o esgotamento profissional."
      },
      {
        title: "Programa de Mindfulness Baseado em Evid\xEAncias (MBSR/MBCT)",
        description: "Programa de grupo em protocolos internacionalmente validados (MBSR e MBCT) para redu\xE7\xE3o de stress e preven\xE7\xE3o de reca\xEDda em quadros ansiosos e depressivos."
      },
      {
        title: "Programa de Envelhecimento Ativo",
        description: "Estimula\xE7\xE3o cognitiva, atividade f\xEDsica adaptada, engajamento social e atividades domiciliares complementares, direcionado a idosos e \xE0s suas fam\xEDlias."
      },
      {
        title: "Programa Escolar de Preven\xE7\xE3o em Sa\xFAde Mental",
        description: "Programa institucional para escolas com oficinas tem\xE1ticas, compet\xEAncias socioemocionais, preven\xE7\xE3o de bullying, manejo de stress e capacita\xE7\xE3o docente."
      }
    ]
  },
  {
    id: "reciclagem-sustentabilidade",
    title: "Reciclagem e sustentabilidade",
    short: "Sustentabilidade",
    summary: "Sensibiliza\xE7\xE3o ambiental e capacita\xE7\xE3o pr\xE1tica em gest\xE3o de res\xEDduos para institui\xE7\xF5es.",
    gradient: "from-lime-600 to-green-700",
    accent: "text-lime-700",
    icon: "handHeart",
    items: [
      {
        title: "Conscientiza\xE7\xE3o Ambiental",
        description: "Sess\xF5es formativas sobre impacto ambiental, pr\xE1ticas sustent\xE1veis e responsabilidade ecol\xF3gica institucional, adaptadas ao contexto de Mo\xE7ambique."
      },
      {
        title: "Treinamento em Gest\xE3o de Res\xEDduos",
        description: "Forma\xE7\xE3o pr\xE1tica sobre gest\xE3o de res\xEDduos, separa\xE7\xE3o, redu\xE7\xE3o e pr\xE1ticas sustent\xE1veis aplic\xE1veis ao contexto organizacional."
      }
    ]
  }
];

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "Listar categorias de servi\xE7os",
  description: "Lista as categorias do cat\xE1logo de servi\xE7os da Tikvah com um resumo de cada uma.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const categories = TIKVAH_CATEGORIES.map((category) => ({
      id: category.id,
      title: category.title,
      summary: category.summary,
      itemCount: category.items.length
    }));
    return {
      content: [
        {
          type: "text",
          text: `${TIKVAH_INTRO}

${categories.map((c) => `- ${c.title} (${c.id}): ${c.summary}`).join("\n")}`
        }
      ],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/get-service-category.ts
import { ToolError, defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^4.6.5";
var get_service_category_default = defineTool2({
  name: "get_service_category",
  title: "Detalhe de uma categoria de servi\xE7os",
  description: "Devolve todos os servi\xE7os de uma categoria do cat\xE1logo Tikvah, a partir do seu id.",
  inputSchema: {
    category_id: z.string().min(1).describe("Id da categoria, por exemplo 'saude-mental'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category_id }) => {
    const category = TIKVAH_CATEGORIES.find((c) => c.id === category_id);
    if (!category) {
      throw new ToolError(
        `Categoria desconhecida: ${category_id}. Ids v\xE1lidos: ${TIKVAH_CATEGORIES.map((c) => c.id).join(", ")}`
      );
    }
    const detail = {
      id: category.id,
      title: category.title,
      summary: category.summary,
      items: category.items.map((item) => ({
        title: item.title,
        description: item.description
      }))
    };
    return {
      content: [
        {
          type: "text",
          text: `${detail.title}
${detail.summary}

${detail.items.map((i) => `- ${i.title}: ${i.description}`).join("\n")}`
        }
      ],
      structuredContent: { category: detail }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/data/blog-posts.ts
var DEFAULT_IMAGE = "/og-image.jpg";
var BLOG_POSTS = [
  {
    slug: "redes-sociais-oportunidades-ou-conflitos",
    title: "Redes Sociais: ferramenta de oportunidades ou fonte de conflitos?",
    description: "An\xE1lise dual \u2014 psican\xE1lise e ciberseguran\xE7a \u2014 sobre o tempo nas redes sociais e o seu impacto na sa\xFAde psicol\xF3gica.",
    image: DEFAULT_IMAGE,
    datePublished: "2026-06-03",
    dateModified: "2026-06-03"
  },
  {
    slug: "act-terapia-contextos-africanos",
    title: "ACT: Terapia de Aceita\xE7\xE3o e Compromisso em Contextos Africanos",
    description: "Aplica\xE7\xE3o da Acceptance and Commitment Therapy (ACT) em contextos africanos, com adapta\xE7\xE3o cultural e integra\xE7\xE3o com valores comunit\xE1rios tradicionais.",
    image: DEFAULT_IMAGE,
    datePublished: "2024-08-19",
    dateModified: "2024-08-19"
  },
  {
    slug: "mbsr-meta-analise-eficacia",
    title: "MBSR: Meta-An\xE1lise da Efic\xE1cia em Sa\xFAde Mental",
    description: "Revis\xE3o sistem\xE1tica e meta-an\xE1lise sobre a efic\xE1cia do Mindfulness-Based Stress Reduction (MBSR) em diversas popula\xE7\xF5es cl\xEDnicas.",
    image: DEFAULT_IMAGE,
    datePublished: "2024-08-01",
    dateModified: "2024-08-01"
  },
  {
    slug: "psicologia-organizacional-transformacao-digital",
    title: "Psicologia Organizacional e Transforma\xE7\xE3o Digital",
    description: "Como a psicologia organizacional apoia processos de transforma\xE7\xE3o digital, gest\xE3o da mudan\xE7a e bem-estar no trabalho.",
    image: DEFAULT_IMAGE,
    datePublished: "2024-08-19",
    dateModified: "2024-08-19"
  },
  {
    slug: "trauma-cultural-resiliencia-pos-colonial",
    title: "Trauma Cultural e Resili\xEAncia P\xF3s-Colonial",
    description: "Compreender o trauma cultural em contextos p\xF3s-coloniais africanos e estrat\xE9gias de resili\xEAncia comunit\xE1ria.",
    image: DEFAULT_IMAGE,
    datePublished: "2024-07-28",
    dateModified: "2024-07-28"
  }
];

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "Listar artigos do blog",
  description: "Lista os artigos publicados no blog da Tikvah, com slug, t\xEDtulo e data.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const posts = BLOG_POSTS.map((post) => ({
      slug: post.slug,
      title: post.title,
      description: post.description,
      datePublished: post.datePublished,
      url: `https://tikvahpsycem.lovable.app/blog/${post.slug}`
    }));
    return {
      content: [
        {
          type: "text",
          text: posts.map((p) => `- ${p.datePublished} \u2014 ${p.title} (${p.url})`).join("\n")
        }
      ],
      structuredContent: { posts }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-appointments.ts
var list_appointments_default = defineTool4({
  name: "list_appointments",
  title: "Listar marca\xE7\xF5es",
  description: "Lista as marca\xE7\xF5es mais recentes a que o utilizador autenticado tem acesso. O acesso \xE9 controlado pelas regras de seguran\xE7a da base de dados.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("N\xFAmero m\xE1ximo de marca\xE7\xF5es a devolver (por omiss\xE3o 10)."),
    status: z2.string().trim().min(1).optional().describe("Filtrar por estado da marca\xE7\xE3o, por exemplo 'pending'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "\xC9 necess\xE1rio iniciar sess\xE3o." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("appointments").select("id, client_name, service_type, preferred_date, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const appointments = (data ?? []).map((row) => ({
      id: row.id,
      clientName: row.client_name,
      serviceType: row.service_type,
      preferredDate: row.preferred_date,
      status: row.status,
      createdAt: row.created_at
    }));
    return {
      content: [
        {
          type: "text",
          text: appointments.length ? appointments.map((a) => `- ${a.preferredDate} \u2014 ${a.clientName} (${a.serviceType}) [${a.status}]`).join("\n") : "Sem marca\xE7\xF5es acess\xEDveis para esta conta."
        }
      ],
      structuredContent: { appointments }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rrlwabtzwvurhhfwpmiq";
var mcp_default = defineMcp({
  name: "tikvahpsycem",
  title: "tikvahpsycem",
  version: "0.1.0",
  instructions: "Ferramentas da Tikvah Psycem. Use `list_services` e `get_service_category` para o cat\xE1logo de servi\xE7os, `list_blog_posts` para artigos publicados e `list_appointments` para marca\xE7\xF5es acess\xEDveis \xE0 conta autenticada.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, get_service_category_default, list_blog_posts_default, list_appointments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
